### ISSUE TITLE
Hello, World.

### ISSUE THREAD

**Issue by wuxian425** [Slouchwind/something-useless#1]
# Hello, World!
###### Hello, World!

Hello, World!   
*Hello, World!*   
**Hello, World!**   
***Hello, World!***   
`Hello, World!`   

```
Hello, World!
```

~Hello, World!~

**Comment by Slouchwind** [comment]
???

**Comment by Slouchwind** [comment]
It's "!", not ".".
And it's also not includes ","

**Comment by wuxian425** [comment]
> It's "!", not ".". And it's also not includes ","

我不管我不管（雾

**Comment by Slouchwind** [comment]
> 

6

**Comment by wuxian425** [comment]
正确的应该是「Hello, World!」。
